apiVersion: v2
appVersion: v2021.09.09
dependencies:
- condition: kubedb-catalog.enabled
  name: kubedb-catalog
  repository: https://charts.appscode.com/stable/
  version: v2021.09.09
- condition: kubedb-community.enabled
  name: kubedb-community
  repository: https://charts.appscode.com/stable/
  version: v0.21.0
- condition: kubedb-enterprise.enabled
  name: kubedb-enterprise
  repository: https://charts.appscode.com/stable/
  version: v0.8.0
- condition: kubedb-autoscaler.enabled
  name: kubedb-autoscaler
  repository: https://charts.appscode.com/stable/
  version: v0.6.0
- condition: kubedb-metrics.enabled
  name: kubedb-metrics
  repository: https://charts.appscode.com/stable/
  version: v2021.09.09
description: KubeDB by AppsCode - Production ready databases on Kubernetes
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb
sources:
- https://github.com/kubedb
type: application
version: v2021.09.09
