apiVersion: v1
appVersion: v0.8.0
description: KubeDB Enterprise by AppsCode - Enterprise features for KubeDB
home: https://kubedb.com
icon: https://cdn.appscode.com/images/products/kubedb/kubedb-enterprise-icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: kubedb-enterprise
sources:
- https://github.com/kubedb
version: v0.8.0
